"use client";
import {useEffect,useState} from "react";
import {useParams} from "next/navigation";
import Link from "next/link";
import {supabase} from "../../../lib/supabase";
import FollowButton from "../../../components/FollowButton";
import HoopLoading from "../../../components/HoopLoading";

export default function WomensTeam(){
 const {id}=useParams<{id:string}>(); const [team,setTeam]=useState<any>(null); const [reviews,setReviews]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [canViewReviews,setCanViewReviews]=useState(false); const [canSeeRatings,setCanSeeRatings]=useState(false); const [canReview,setCanReview]=useState(false); const [ratingAverage,setRatingAverage]=useState<number|null>(null); const [ratingCount,setRatingCount]=useState(0);
 useEffect(()=>{(async()=>{const {data:t}=await supabase.from("womens_teams").select("id,name,country,city,league_id,league_name").eq("id",id).maybeSingle();setTeam(t); const {data:{user}}=await supabase.auth.getUser(); if(user){const [{data:p},{data:s}]=await Promise.all([supabase.from("profiles").select("account_type,basketball_type,player_verified,selected_womens_team_id").eq("id",user.id).maybeSingle(),supabase.from("subscriptions").select("plan,status,current_period_end").eq("user_id",user.id).maybeSingle()]); const active=["active","trialing"].includes(s?.status||"")&&(!s?.current_period_end||new Date(s.current_period_end)>new Date()); const premiumFan=p?.account_type==="fan"&&s?.plan==="premium"; setCanSeeRatings(active); setCanViewReviews(active&&!premiumFan); setCanReview(p?.account_type==="player"&&p?.basketball_type==="womens"&&Boolean(p?.player_verified)&&p?.selected_womens_team_id===id); if(active){const {data:ratingRows}=await supabase.from("womens_team_reviews").select("overall_rating").eq("womens_team_id",id).eq("status","approved"); const nums=(ratingRows||[]).map((x:any)=>Number(x.overall_rating)).filter((n:number)=>Number.isFinite(n)); setRatingCount(nums.length); setRatingAverage(nums.length?nums.reduce((a:number,b:number)=>a+b,0)/nums.length:null); const {data:r}=await supabase.from("womens_team_reviews").select("id,title,body,overall_rating,created_at,is_anonymous").eq("womens_team_id",id).eq("status","approved").order("created_at",{ascending:false});setReviews(r||[])}} setLoading(false)})()},[id]);
 if(loading)return <main className="page-shell"><div className="page-container"><HoopLoading label="Loading women’s team..." /></div></main>;
 if(!team)return <main className="page-shell"><div className="page-container"><section className="hero-card"><h1>Women’s team not found</h1><Link href="/womens" className="btn">Back to Women’s Basketball</Link></section></div></main>;
 const average=ratingAverage;
 return <main className="page-shell"><div className="page-container"><header className="topbar"><Link href="/" className="brand">HoopCheck</Link><nav className="topnav"><Link href="/womens">Women’s Basketball</Link><Link href="/search">Search</Link><Link href="/profile">Profile</Link></nav></header>
 <section className="hero-card"><p className="eyebrow">WOMEN’S TEAM PROFILE</p><h1>{team.name}</h1><p className="muted">{team.city?team.city+", ":""}{team.country||"International"} · {team.league_name||"Professional"}</p><div className="actions"><FollowButton targetType="team" targetId={team.id}/>{canReview&&<Link href={"/womens/"+team.id+"/review"} className="btn">Write A Review</Link>}</div></section>
 <section className="grid compact-grid"><div className="card"><span className="card-kicker">RATING</span><h2>{average===null?"—":average.toFixed(1)+"/5"}</h2><p className="muted">{canSeeRatings?ratingCount+" published review"+(ratingCount===1?"":"s"):"Ratings only for Premium Fans"}</p></div><div className="card"><span className="card-kicker">LEAGUE</span><h2>{team.league_name||"Professional"}</h2><p className="muted">{team.country||"International"}</p></div></section>
 <section className="dashboard-card compact-section">{canViewReviews?<><p className="eyebrow">PLAYER EXPERIENCES</p><h2>Ratings & Reviews</h2>{reviews.map(r=><article className="compact-review" key={r.id}><div className="review-line"><strong>{r.title||"Player experience"}</strong><strong>{Number(r.overall_rating).toFixed(1)}/5</strong></div><p>{r.body}</p><small className="muted">{new Date(r.created_at).toLocaleDateString()}</small></article>)}{!reviews.length&&<p className="muted">No published reviews yet.</p>}</>:canSeeRatings?<><p className="eyebrow">PREMIUM FAN VIEW</p><h2>Ratings available</h2><p className="muted">Premium Fans can see the team rating, but published review text is reserved for eligible non-fan members.</p></>:<><p className="eyebrow">MEMBERSHIP</p><h2>Ratings & reviews are member features</h2><p className="muted">Join Pro or Premium to unlock the full women’s team experience.</p><Link href="/membership" className="btn">View Membership</Link></>}</section>
 <div className="bottom-back"><button type="button" className="btn dark" onClick={()=>window.history.back()}>← Back</button></div></div></main>;
}