"use client";
import {useEffect,useState} from "react"; import Link from "next/link"; import {supabase} from "../../../lib/supabase";
type Report={id:string;profile_id:string;reporter_id:string;reason:string;status:string;created_at:string};
type Profile={id:string;display_name:string|null;username:string|null;account_type:string;moderation_status:string};
export default function ProfileReportsAdmin(){
 const [reports,setReports]=useState<Report[]>([]);const [profiles,setProfiles]=useState<Record<string,Profile>>({});const [error,setError]=useState("");
 async function load(){const {data:r,error:e}=await supabase.from("profile_reports").select("id,profile_id,reporter_id,reason,status,created_at").order("created_at",{ascending:false});if(e){setError(e.message);return;}setReports(r||[]);const ids=(r||[]).map(x=>x.profile_id);if(ids.length){const {data:p}=await supabase.from("profiles").select("id,display_name,username,account_type,moderation_status").in("id",ids);const m:Record<string,Profile>={};for(const x of p||[])m[x.id]=x;setProfiles(m);}}
 useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){location.href="/login";return;}const {data:ok}=await supabase.rpc("is_current_user_admin_or_moderator");if(!ok){location.href="/dashboard";return;}load()})()},[]);
 async function resolve(id:string,status:"resolved"|"dismissed"){const {error:e}=await supabase.rpc("admin_resolve_profile_report",{p_report_id:id,p_status:status});if(e){setError(e.message);return;}load();}
 return <main className="page-shell"><div className="page-container"><header className="topbar"><Link href="/admin/directory" className="brand">HOOPCHECK ADMIN</Link><nav className="topnav"><Link href="/admin/users">Users</Link><Link href="/admin/reviews">Reviews</Link></nav></header><section className="hero-card"><p className="eyebrow">ADMIN · PROFILE REPORTS</p><h1>Account flags</h1><p className="muted">Review reports submitted by research users and take moderation action.</p></section>{error&&<div className="message error" style={{marginTop:16}}>{error}</div>}<section style={{display:"grid",gap:14,marginTop:20}}>{reports.map(r=>{const p=profiles[r.profile_id];return <article className="dashboard-card" key={r.id}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><span className="card-kicker">{r.status.toUpperCase()}</span><h2>{p?.display_name||p?.username||"Profile"}</h2><p className="muted">{p?.account_type?.toUpperCase()} · Current flag: {p?.moderation_status}</p></div><small className="muted">{new Date(r.created_at).toLocaleString()}</small></div><p><strong>Reason:</strong> {r.reason}</p>{r.status==="open"&&<div style={{display:"flex",gap:10,flexWrap:"wrap"}}><Link className="btn" href={"/players/"+r.profile_id}>Open Profile</Link><Link className="btn dark" href={"/admin/users"}>Moderate User</Link><button className="btn dark" onClick={()=>resolve(r.id,"resolved")}>Resolve</button><button className="btn dark" onClick={()=>resolve(r.id,"dismissed")}>Dismiss</button></div>}</article>})}{!reports.length&&<div className="dashboard-card">No profile reports.</div>}</section></div></main>;
}