"use client";
import {supabase} from "../../lib/supabase";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import FollowButton from "../../components/FollowButton";
import HoopLoading from "../../components/HoopLoading";

export default function Womens(){
 const [teams,setTeams]=useState<any[]>([]); const [leagues,setLeagues]=useState<any[]>([]); const [q,setQ]=useState(""); const [country,setCountry]=useState(""); const [league,setLeague]=useState(""); const [loading,setLoading]=useState(true);
 useEffect(()=>{let mounted=true;Promise.race([Promise.all([supabase.from("womens_teams").select("id,name,country,city,league_id,league_name").eq("active",true).order("name"),supabase.from("womens_leagues").select("id,name,country,level").eq("active",true).order("name")]),new Promise<any>(resolve=>setTimeout(()=>resolve([{data:[]},{data:[]}]),2500))]).then(([t,l])=>{if(!mounted)return;setTeams(t.data||[]);setLeagues(l.data||[]);setLoading(false)});return()=>{mounted=false}},[]);
 const countries=useMemo(()=>Array.from(new Set(teams.map(t=>t.country).filter(Boolean))).sort(),[teams]);
 const filtered=useMemo(()=>teams.filter(t=>(!q||[t.name,t.city,t.country,t.league_name].join(" ").toLowerCase().includes(q.toLowerCase()))&&(!country||t.country===country)&&(!league||t.league_id===league)),[teams,q,country,league]);
 return <main className="page-shell"><div className="page-container"><header className="topbar"><Link href="/" className="brand">HoopCheck</Link><nav className="topnav"><Link href="/teams">Men’s HoopCheck</Link><Link href="/search">Search</Link><Link href="/profile">Profile</Link></nav></header>
 <section className="hero-card compact-hero"><p className="eyebrow">WOMEN’S BASKETBALL</p><h1>Women’s HoopCheck</h1><p className="muted">Research women’s professional teams and leagues with the same core HoopCheck membership, following, ratings and review experience.</p><div className="actions"><Link href="/teams" className="btn dark">Men’s Basketball</Link></div></section>
 <section className="dashboard-card compact-section"><div className="research-search"><div className="search-label">WOMEN’S DIRECTORY</div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search teams, cities, countries..." /><div className="team-filter-row"><select value={country} onChange={e=>setCountry(e.target.value)}><option value="">All countries</option>{countries.map(c=><option key={c} value={c}>{c}</option>)}</select><select value={league} onChange={e=>setLeague(e.target.value)}><option value="">All leagues</option>{leagues.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></div></div></section>
 <section className="compact-section"><div className="section-heading"><div><p className="eyebrow">LEAGUES</p><h2>Women’s leagues</h2></div><span className="muted">{leagues.length} leagues</span></div><div className="league-filter-grid">{leagues.map(l=><button key={l.id} className={league===l.id?"filter-chip active":"filter-chip"} onClick={()=>setLeague(league===l.id?"":l.id)}><strong>{l.name}</strong><span>{l.country||"International"}{l.level?" · "+l.level:""}</span></button>)}</div></section>
 {loading?<div className="dashboard-card"><HoopLoading label="Loading women’s basketball..." /></div>:<section className="grid compact-grid">{filtered.map(t=><article className="dashboard-card compact-card" key={t.id}><span className="card-kicker">{t.league_name||"Women’s Basketball"}</span><h2>{t.name}</h2><p className="muted">{t.city?t.city+", ":""}{t.country||"International"}</p><div className="actions"><FollowButton targetType="team" targetId={t.id}/><Link href={"/womens/"+t.id} className="btn dark">View Profile</Link></div></article>)}{!filtered.length&&<div className="dashboard-card"><h2>No women’s teams found.</h2><p className="muted">Try another country, league, or search.</p></div>}</section>}
 <div className="bottom-back"><button type="button" className="btn dark" onClick={()=>window.history.back()}>← Back</button></div></div></main>
}
