"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { supabase } from "../../../lib/supabase";

type UserRow={id:string;email:string|null;display_name:string|null;username:string|null;account_type:string;player_verified:boolean;moderation_status:string;moderation_note:string|null;avatar_url:string|null;avatar_moderation_status:string;bio:string|null;current_country:string|null;current_team:string|null;profile_visibility:string;free_agent:boolean;interests:string|null;favorite_leagues:string|null;created_at:string};

export default function AdminUsersPage(){
 const [rows,setRows]=useState<UserRow[]>([]); const [type,setType]=useState(""); const [q,setQ]=useState(""); const [selected,setSelected]=useState<UserRow|null>(null); const [status,setStatus]=useState("normal"); const [note,setNote]=useState(""); const [avatarStatus,setAvatarStatus]=useState("approved"); const [accountType,setAccountType]=useState("player"); const [verified,setVerified]=useState(false); const [visibility,setVisibility]=useState("public"); const [freeAgent,setFreeAgent]=useState(false); const [bio,setBio]=useState(""); const [currentCountry,setCurrentCountry]=useState(""); const [currentTeam,setCurrentTeam]=useState(""); const [interests,setInterests]=useState(""); const [favoriteLeagues,setFavoriteLeagues]=useState(""); const [message,setMessage]=useState("");
 async function load(){const {data}=await supabase.rpc("admin_list_users",{p_account_type:type||null,p_query:q.trim()||null});setRows((data||[]) as UserRow[]);}
 useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){location.href="/login";return;}const {data:ok}=await supabase.rpc("is_current_user_admin_or_moderator");if(!ok){location.href="/dashboard";return;}await load();})();},[]);
 function pick(r:UserRow){setSelected(r);setStatus(r.moderation_status);setNote(r.moderation_note||"");setAvatarStatus(r.avatar_moderation_status);setAccountType(r.account_type);setVerified(r.player_verified);setVisibility(r.profile_visibility||"public");setFreeAgent(!!r.free_agent);setBio(r.bio||"");setCurrentCountry(r.current_country||"");setCurrentTeam(r.current_team||"");setInterests(r.interests||"");setFavoriteLeagues(r.favorite_leagues||"");setMessage("");}
 async function save(){if(!selected)return;setMessage("");const {error}=await supabase.rpc("admin_update_profile",{p_profile_id:selected.id,p_account_type:accountType,p_player_verified:verified,p_moderation_status:status,p_moderation_note:note||null,p_avatar_moderation_status:avatarStatus,p_avatar_moderation_note:avatarStatus==="approved"?"Approved by admin":null,p_profile_visibility:visibility,p_free_agent:freeAgent,p_bio:bio,p_current_country:currentCountry,p_current_team:currentTeam,p_interests:interests,p_favorite_leagues:favoriteLeagues});if(error){setMessage(error.message);return;}setMessage("User updated.");await load();}
 return <main className="page-shell"><div className="page-container"><header className="topbar"><Link href="/admin/directory" className="brand">HOOPCHECK ADMIN</Link><nav className="topnav"><Link href="/admin/reviews">Reviews</Link><Link href="/admin/verification">Verification</Link><Link href="/dashboard">Dashboard</Link></nav></header>
 <section className="hero-card"><p className="eyebrow">ADMIN · USERS</p><h1>User & Player Control</h1><p className="muted">Look up any account, filter by account type, review verification, warn/flag profiles, and moderate profile photos.</p></section>
 <section className="dashboard-card" style={{marginTop:20}}><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search email, username, name" style={{flex:"1 1 260px"}}/><select value={type} onChange={e=>setType(e.target.value)}><option value="">All account types</option><option value="player">Players</option><option value="coach">Coaches</option><option value="scout">Scouts</option><option value="agent">Agents</option><option value="fan">Fans</option></select><button className="btn" onClick={load}>Search</button></div></section>
 <section style={{display:"grid",gridTemplateColumns:"minmax(0,1.3fr) minmax(300px,.7fr)",gap:18,marginTop:18}}>
 <div style={{display:"grid",gap:10}}>{rows.map(r=><button key={r.id} onClick={()=>pick(r)} style={{textAlign:"left",background:"var(--card)",color:"inherit",border:"1px solid var(--border)",borderRadius:12,padding:15,cursor:"pointer"}}><strong>{r.display_name||r.username||"Unnamed user"}</strong><div className="muted" style={{fontSize:12}}>{r.email} · {r.account_type.toUpperCase()} · {r.player_verified?"VERIFIED":"UNVERIFIED"} · {r.moderation_status.toUpperCase()}</div></button>)}{!rows.length&&<div className="dashboard-card">No users match the filter.</div>}</div>
 <aside className="dashboard-card">{!selected?<><h2>Select a user</h2><p className="muted">Choose an account to edit.</p></>:<><p className="eyebrow">EDIT USER</p><h2>{selected.display_name||selected.username}</h2><p className="muted">{selected.email}</p>{selected.avatar_url&&<img src={selected.avatar_url} alt="" style={{width:80,height:80,borderRadius:"50%",objectFit:"cover"}}/>}<label>Account type<select value={accountType} onChange={e=>setAccountType(e.target.value)}><option value="player">Player</option><option value="coach">Coach</option><option value="scout">Scout</option><option value="agent">Agent</option><option value="fan">Fan</option></select></label><label><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/> Verified player</label><label>Profile status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="normal">Normal</option><option value="warned">Warned</option><option value="flagged">Flagged</option><option value="suspended">Suspended</option></select></label><label>Profile visibility<select value={visibility} onChange={e=>setVisibility(e.target.value)}><option value="public">Public</option><option value="private">Private</option></select></label><label><input type="checkbox" checked={freeAgent} onChange={e=>setFreeAgent(e.target.checked)}/> Mark as free agent</label><label>Current country<input value={currentCountry} onChange={e=>setCurrentCountry(e.target.value)} /></label><label>Current team<input value={currentTeam} onChange={e=>setCurrentTeam(e.target.value)} /></label><label>Bio<textarea value={bio} onChange={e=>setBio(e.target.value)} rows={4}/></label><label>Interests<textarea value={interests} onChange={e=>setInterests(e.target.value)} rows={3}/></label><label>Favorite leagues<textarea value={favoriteLeagues} onChange={e=>setFavoriteLeagues(e.target.value)} rows={3}/></label><label>Moderator note<textarea value={note} onChange={e=>setNote(e.target.value)} rows={4}/></label><label>Avatar moderation<select value={avatarStatus} onChange={e=>setAvatarStatus(e.target.value)}><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></label><button className="btn" onClick={save}>Save moderation changes</button>{message&&<p className="muted">{message}</p>}</>}</aside></section></div></main>;
}