-- Expand global team directory: North America outside the United States + Asia.
insert into public.teams (name,country,league_name,city,active,source)
select v.name,v.country,v.league_name,v.city,true,'hoopcheck_global_expansion'
from (values
('Toronto Raptors','Canada','NBA','Toronto'),('Vancouver Bandits','Canada','CEBL','Vancouver'),('Calgary Surge','Canada','CEBL','Calgary'),('Edmonton Stingers','Canada','CEBL','Edmonton'),('Montreal Alliance','Canada','CEBL','Montreal'),('Niagara River Lions','Canada','CEBL','St. Catharines'),('Ottawa BlackJacks','Canada','CEBL','Ottawa'),('Scarborough Shooting Stars','Canada','CEBL','Scarborough'),('Saskatchewan Rattlers','Canada','CEBL','Saskatoon'),('Winnipeg Sea Bears','Canada','CEBL','Winnipeg'),
('Capitanes de Ciudad de México','Mexico','NBA G League','Mexico City'),('Soles de Mexicali','Mexico','LNBP','Mexicali'),('Fuerza Regia','Mexico','LNBP','Monterrey'),('Astros de Jalisco','Mexico','LNBP','Guadalajara'),('Panteras de Aguascalientes','Mexico','LNBP','Aguascalientes'),('Diablos Rojos del México','Mexico','LNBP','Mexico City'),('Halcones de Xalapa','Mexico','LNBP','Xalapa'),('Plateros de Fresnillo','Mexico','LNBP','Fresnillo'),('Mineros de Zacatecas','Mexico','LNBP','Zacatecas'),('Abejas de León','Mexico','LNBP','León'),
('Alvark Tokyo','Japan','B.League','Tokyo'),('Chiba Jets','Japan','B.League','Chiba'),('Ryukyu Golden Kings','Japan','B.League','Okinawa'),('Utsunomiya Brex','Japan','B.League','Utsunomiya'),('San-en NeoPhoenix','Japan','B.League','Toyohashi'),('Seoul SK Knights','South Korea','KBL','Seoul'),('Anyang Jung Kwan Jang Red Boosters','South Korea','KBL','Anyang'),('Busan KCC Egis','South Korea','KBL','Busan'),('Changwon LG Sakers','South Korea','KBL','Changwon'),('Suwon KT Sonicboom','South Korea','KBL','Suwon'),
('Beijing Ducks','China','CBA','Beijing'),('Guangdong Southern Tigers','China','CBA','Dongguan'),('Liaoning Flying Leopards','China','CBA','Shenyang'),('Shanghai Sharks','China','CBA','Shanghai'),('Zhejiang Lions','China','CBA','Hangzhou'),('Nanjing Monkey Kings','China','CBA','Nanjing'),('Xinjiang Flying Tigers','China','CBA','Urumqi'),('TaiwanBeer HeroBears','Taiwan','TPBL','Taipei'),('New Taipei Kings','Taiwan','P.League+','New Taipei'),('Taoyuan Pauian Pilots','Taiwan','TPBL','Taoyuan'),
('San Miguel Beermen','Philippines','PBA','Manila'),('Barangay Ginebra San Miguel','Philippines','PBA','Manila'),('TNT Tropang Giga','Philippines','PBA','Manila'),('Meralco Bolts','Philippines','PBA','Pasig'),('Magnolia Chicken Timplados Hotshots','Philippines','PBA','Manila'),('Pelita Jaya Basketball','Indonesia','IBL','Jakarta'),('Satria Muda Pertamina','Indonesia','IBL','Jakarta'),('Prawira Bandung','Indonesia','IBL','Bandung'),('Dewa United Banten','Indonesia','IBL','Tangerang'),
('Al Riyadi Beirut','Lebanon','Lebanese Basketball League','Beirut'),('Sagesse SC','Lebanon','Lebanese Basketball League','Beirut'),('Shahrdari Gorgan','Iran','Iranian Basketball Super League','Gorgan'),('Petrochimi Bandar Imam','Iran','Iranian Basketball Super League','Bandar Imam'),('Al Ahli Saudi','Saudi Arabia','Saudi Basketball League','Jeddah'),('Al Hilal Saudi','Saudi Arabia','Saudi Basketball League','Riyadh'),('Al Nassr Saudi','Saudi Arabia','Saudi Basketball League','Riyadh'),('Al Rayyan','Qatar','Qatar Basketball League','Doha'),('Al Sadd','Qatar','Qatar Basketball League','Doha'),('Shabab Al Ahli','United Arab Emirates','UAE National Basketball League','Dubai'),('Al Wasl','United Arab Emirates','UAE National Basketball League','Dubai'),('Maccabi Tel Aviv','Israel','Israeli Basketball Premier League','Tel Aviv'),('Hapoel Jerusalem','Israel','Israeli Basketball Premier League','Jerusalem')
) as v(name,country,league_name,city)
where not exists (select 1 from public.teams t where lower(t.name)=lower(v.name) and lower(coalesce(t.country,''))=lower(v.country));