-- Curated professional-team expansion requested for HoopCheck's global directory.
insert into public.teams (name,country,league_name,city,active,source)
select v.name,v.country,v.league_name,v.city,true,'HoopCheck 2026 league expansion'
from (values
('Maccabi Ramat Gan','Israel','Israeli Basketball Premier League','Ramat Gan'),
('Hapoel Gilboa Galil','Israel','Israeli Basketball Premier League','Gilboa'),
('Bnei Herzliya','Israel','Israeli Basketball Premier League','Herzliya'),
('Hapoel Holon','Israel','Israeli Basketball Premier League','Holon'),
('Hapoel Be''er Sheva','Israel','Israeli Basketball Premier League','Be''er Sheva'),
('Ironi Ness Ziona','Israel','Israeli Basketball Premier League','Ness Ziona'),
('Ironi Kiryat Ata','Israel','Israeli Basketball Premier League','Kiryat Ata'),
('Maccabi Rishon LeZion','Israel','Israeli Basketball Premier League','Rishon LeZion'),
('ERA Nymburk','Czech Republic','NBL','Nymburk'),
('BK Opava','Czech Republic','NBL','Opava'),
('BK Děčín','Czech Republic','NBL','Děčín'),
('USK Praha','Czech Republic','NBL','Prague'),
('BK Pardubice','Czech Republic','NBL','Pardubice'),
('SLUNETA Ústí nad Labem','Czech Republic','NBL','Ústí nad Labem'),
('BC Brno','Czech Republic','NBL','Brno'),
('NH Ostrava','Czech Republic','NBL','Ostrava'),
('Helsinki Seagulls','Finland','Korisliiga','Helsinki'),
('Kataja Basket','Finland','Korisliiga','Joensuu'),
('Kauhajoki Karhu Basket','Finland','Korisliiga','Kauhajoki'),
('Kobrat','Finland','Korisliiga','Lapua'),
('Kouvot','Finland','Korisliiga','Kouvola'),
('KTP-Basket','Finland','Korisliiga','Kotka'),
('Lahti Basketball','Finland','Korisliiga','Lahti'),
('Salon Vilpas','Finland','Korisliiga','Salo'),
('Tampereen Pyrintö','Finland','Korisliiga','Tampere'),
('Kobrat Lapua','Finland','Korisliiga','Lapua'),
('KB Trepça','Kosovo','Kosovo Basketball Superleague','Mitrovica'),
('Sigal Prishtina','Kosovo','Kosovo Basketball Superleague','Prishtina'),
('Peja','Kosovo','Kosovo Basketball Superleague','Peja'),
('Bashkimi Prizren','Kosovo','Kosovo Basketball Superleague','Prizren'),
('Golden Eagle Ylli','Kosovo','Kosovo Basketball Superleague','Therandë'),
('Vëllaznimi','Kosovo','Kosovo Basketball Superleague','Gjakova'),
('Rahoveci','Kosovo','Kosovo Basketball Superleague','Rahovec'),
('Benfica','Portugal','Liga Betclic','Lisbon'),
('FC Porto','Portugal','Liga Betclic','Porto'),
('Sporting CP','Portugal','Liga Betclic','Lisbon'),
('Galitos Barreiro','Portugal','Liga Betclic','Barreiro'),
('Esgueira Aveiro OLI','Portugal','Liga Betclic','Aveiro'),
('Imortal Basket','Portugal','Liga Betclic','Albufeira'),
('Ovarense','Portugal','Liga Betclic','Ovar'),
('SC Braga','Portugal','Liga Betclic','Braga'),
('SC Vasco da Gama','Portugal','Liga Betclic','Porto'),
('UD Oliveirense','Portugal','Liga Betclic','Oliveira de Azeméis'),
('Vitória SC','Portugal','Liga Betclic','Guimarães'),
('CAB Madeira','Portugal','Proliga','Funchal'),
('Illiabum Clube','Portugal','Proliga','Ílhavo'),
('VEF Rīga','Latvia','Latvian-Estonian Basketball League','Riga'),
('Rīgas Zeļļi','Latvia','Latvian-Estonian Basketball League','Riga'),
('BK Ventspils','Latvia','Latvian-Estonian Basketball League','Ventspils'),
('BK Liepāja','Latvia','Latvian-Estonian Basketball League','Liepāja'),
('BK Ogre','Latvia','Latvian-Estonian Basketball League','Ogre'),
('Latvijas Universitāte','Latvia','Latvian-Estonian Basketball League','Riga'),
('Valmiera Glass VIA','Latvia','Latvian-Estonian Basketball League','Valmiera'),
('CSM Corona Brașov','Romania','Liga Națională','Brașov'),
('CSM Oradea','Romania','Liga Națională','Oradea'),
('CSM Galați','Romania','Liga Națională','Galați'),
('CSM Târgu Jiu','Romania','Liga Națională','Târgu Jiu'),
('CSM Târgu Mureș','Romania','Liga Națională','Târgu Mureș'),
('CSU Sibiu','Romania','Liga Națională','Sibiu'),
('CS Vâlcea 1924','Romania','Liga Națională','Râmnicu Vâlcea'),
('Dinamo București','Romania','Liga Națională','Bucharest'),
('Rapid București','Romania','Liga Națională','Bucharest'),
('SCM Timișoara','Romania','Liga Națională','Timișoara'),
('SCM U Craiova','Romania','Liga Națională','Craiova'),
('Steaua București','Romania','Liga Națională','Bucharest'),
('Zlatibor Mozzart','Serbia','Basketball League of Serbia','Čajetina'),
('Sloboda Užice','Serbia','Basketball League of Serbia','Užice'),
('Sloga Kraljevo','Serbia','Basketball League of Serbia','Kraljevo'),
('Spartak Office Shoes','Serbia','Basketball League of Serbia','Subotica'),
('SPD Radnički Kragujevac','Serbia','Basketball League of Serbia','Kragujevac'),
('Tamiš','Serbia','Basketball League of Serbia','Pančevo'),
('Vojvodina mts','Serbia','Basketball League of Serbia','Novi Sad'),
('Vršac Meridianbet','Serbia','Basketball League of Serbia','Vršac'),
('OKK Beograd','Serbia','Basketball League of Serbia','Belgrade'),
('Hercegovac Gajdobra','Serbia','Basketball League of Serbia','Gajdobra'),
('Borac Zemun','Serbia','Basketball League of Serbia','Belgrade'),
('Lietkabelis','Lithuania','Lietuvos krepšinio lyga','Panevėžys'),
('Neptūnas Klaipėda','Lithuania','Lietuvos krepšinio lyga','Klaipėda'),
('Juventus Utena','Lithuania','Lietuvos krepšinio lyga','Utena'),
('Nevėžis-Optibet','Lithuania','Lietuvos krepšinio lyga','Kėdainiai'),
('Jonavos CBet','Lithuania','Lietuvos krepšinio lyga','Jonava'),
('Šiauliai','Lithuania','Lietuvos krepšinio lyga','Šiauliai'),
('Mažeikiai','Lithuania','Lietuvos krepšinio lyga','Mažeikiai'),
('Wolves Twinsbet','Lithuania','Lietuvos krepšinio lyga','Vilnius'),
('Cibona','Croatia','Premijer liga','Zagreb'),
('KK Split','Croatia','Premijer liga','Split'),
('Zadar','Croatia','Premijer liga','Zadar'),
('Dubrava Zagreb','Croatia','Premijer liga','Zagreb'),
('Dinamo Zagreb','Croatia','Premijer liga','Zagreb'),
('Šibenka','Croatia','Premijer liga','Šibenik'),
('Dubrovnik','Croatia','Premijer liga','Dubrovnik'),
('Kvarner 2010','Croatia','Premijer liga','Rijeka'),
('Legia Warszawa','Poland','ORLEN Basket Liga','Warsaw'),
('Trefl Sopot','Poland','ORLEN Basket Liga','Sopot'),
('King Szczecin','Poland','ORLEN Basket Liga','Szczecin'),
('Anwil Włocławek','Poland','ORLEN Basket Liga','Włocławek'),
('Czarni Słupsk','Poland','ORLEN Basket Liga','Słupsk'),
('Start Lublin','Poland','ORLEN Basket Liga','Lublin'),
('Arka Gdynia','Poland','ORLEN Basket Liga','Gdynia'),
('GTK Gliwice','Poland','ORLEN Basket Liga','Gliwice'),
('MKS Dąbrowa Górnicza','Poland','ORLEN Basket Liga','Dąbrowa Górnicza'),
('Twarde Pierniki Toruń','Poland','ORLEN Basket Liga','Toruń'),
('IHC Apes','Mongolia','Mongolian National Basketball Association','Ulaanbaatar'),
('BCH Knights','Mongolia','Mongolian National Basketball Association','Ulaanbaatar'),
('Ulaanbaatar XAC','Mongolia','Mongolian National Basketball Association','Ulaanbaatar'),
('TLG Ulaanbaatar','Mongolia','Mongolian National Basketball Association','Ulaanbaatar'),
('BC Tirana','Albania','Albanian Basketball Superliga','Tirana'),
('Partizani Tirana','Albania','Albanian Basketball Superliga','Tirana'),
('Teuta Durrës','Albania','Albanian Basketball Superliga','Durrës'),
('Vllaznia Shkodër','Albania','Albanian Basketball Superliga','Shkodër'),
('Besëlidhja Lezhë','Albania','Albanian Basketball Superliga','Lezhë'),
('Kamza Basket','Albania','Albanian Basketball Superliga','Kamëz'),
('Enisey','Russia','VTB United League','Krasnoyarsk'),
('MBA-MAI','Russia','VTB United League','Moscow'),
('PARMA','Russia','VTB United League','Perm'),
('Samara','Russia','VTB United League','Samara'),
('Dynamo Vladivostok','Russia','VTB United League','Vladivostok'),
('Avtodor','Russia','VTB United League','Saratov'),
('Uralmash','Russia','VTB United League','Yekaterinburg'),
('UNICS','Russia','VTB United League','Kazan'),
('CSKA Moscow','Russia','VTB United League','Moscow'),
('Zenit Saint Petersburg','Russia','VTB United League','Saint Petersburg'),
('Lokomotiv Kuban','Russia','VTB United League','Krasnodar'),
('Astana','Kazakhstan','VTB United League','Astana')
) as v(name,country,league_name,city)
where not exists (select 1 from public.teams t where lower(t.name)=lower(v.name) and lower(coalesce(t.country,''))=lower(v.country));