-- HoopCheck directory expansion applied 2026-10-06
with league_additions(name,country,level,season) as (values
('NBL','Czechia','Top Division','2026-27','manual-curated-2026-27',true),
('Thailand Basketball League','Thailand','Top Division','2026-27','manual-curated-2026-27',true),
('North Macedonia Vtora Liga','North Macedonia','2nd division','2026-27','manual-curated-2026-27',true),
('Malaysian Basketball League','Malaysia','Top Division','2026-27','manual-curated-2026-27',true),
('Basketball National League','South Africa','Top Division','2026-27','manual-curated-2026-27',true),
('Türkiye Basketbol Süper Ligi','Türkiye','Top Division','2026-27','manual-curated-2026-27',true),
('Division Excellence','Morocco','Top Division','2026-27','manual-curated-2026-27',true),
('Basketball Egyptian Super League','Egypt','Top Division','2026-27','manual-curated-2026-27',true),
('Liga WPlay','Colombia','Top Division','2026-27','manual-curated-2026-27',true),
('IBL','Indonesia','Top Division','2026-27','manual-curated-2026-27',true),
('National 1','Senegal','Top Division','2026-27','manual-curated-2026-27',true)
)
insert into public.leagues(name,country,level,season,source,active)
select v.name,v.country,v.level,v.season,'manual-curated-2026-27',true from league_additions v
where not exists (select 1 from public.leagues l where lower(l.name)=lower(v.name) and lower(coalesce(l.country,''))=lower(v.country));

with additions(name,country,city,league_name) as (values
('AE Chalkidas','Greece','Chalkida','Elite League'),
('Akhaltsikhe','Georgia','Akhaltsikhe','Superleague'),
('Al Ahly','Egypt','Cairo','Basketball Egyptian Super League'),
('Al Gezira','Egypt','Cairo','Basketball Egyptian Super League'),
('Al Ittihad Alexandria','Egypt','Alexandria','Basketball Egyptian Super League'),
('Amyntas','Greece','Athens','Elite League'),
('Anadolu Efes','Türkiye','Istanbul','Türkiye Basketbol Süper Ligi'),
('Anagennisi Arkalochori','Greece','Arkalochori','Elite League'),
('AS Douanes','Senegal','Dakar','National 1'),
('AS Salé','Morocco','Salé','Division Excellence'),
('ASC Ville de Dakar','Senegal','Dakar','National 1'),
('ASCC Bopp','Senegal','Dakar','National 1'),
('Bahçeşehir Koleji','Türkiye','Istanbul','Türkiye Basketbol Süper Ligi'),
('Basketball Löwen Braunschweig','Germany','Braunschweig','ProA'),
('Baskets Juniors TSG Westerstede','Germany','Westerstede','ProB'),
('BBA Hagen','Germany','Hagen','ProB'),
('BC Brno','Czechia','Brno','NBL'),
('Beşiktaş Emlakjet','Türkiye','Istanbul','Türkiye Basketbol Süper Ligi'),
('BG Göttingen','Germany','Göttingen','ProA'),
('BK ARMEX Děčín','Czechia','Děčín','NBL'),
('BK NH Ostrava','Czechia','Ostrava','NBL'),
('BK Olomoucko','Czechia','Olomouc','NBL'),
('BK Opava','Czechia','Opava','NBL'),
('BK Pardubice','Czechia','Pardubice','NBL'),
('Black Fortress','Georgia',null,'Superleague'),
('Bogor Hornbills','Indonesia','Bogor','IBL'),
('Boulogne Côte d’Opale Basketball','France','Boulogne-sur-Mer','NM1'),
('BSW Sixers','Germany','Sandersdorf-Brehna','ProB'),
('Búcaros de Santander','Colombia','Bucaramanga','Liga WPlay'),
('Bursaspor','Türkiye','Bursa','Türkiye Basketbol Süper Ligi'),
('Cafeteros de Armenia','Colombia','Armenia','Liga WPlay'),
('Cajasiete Gran Canaria','Spain','Las Palmas de Gran Canaria','Primera FEB'),
('Cape Town Tigers','South Africa','Cape Town','Basketball National League'),
('Caribbean Storm','Colombia','San Andrés','Liga WPlay'),
('Cimarrones del Chocó','Colombia','Quibdó','Liga WPlay'),
('Culture City Weimar','Germany','Weimar','ProB'),
('Dakar Université Club','Senegal','Dakar','National 1'),
('Darüşşafaka','Türkiye','Istanbul','Türkiye Basketbol Süper Ligi'),
('Dewa United Banten','Indonesia','Banten','IBL'),
('Doxa Lefkadas','Greece','Lefkada','Greek Basketball League'),
('Dunkin Ratchaburi','Thailand','Ratchaburi','Thailand Basketball League'),
('Egoli Magic','South Africa','Johannesburg','Basketball National League'),
('El Geish','Egypt','Cairo','Basketball Egyptian Super League'),
('EN BASKETS Schwelm','Germany','Schwelm','ProB'),
('ERA Nymburk','Czechia','Nymburk','NBL'),
('Fenerbahçe Beko','Türkiye','Istanbul','Türkiye Basketbol Süper Ligi'),
('Fibwi Mallorca Basquet Palma','Spain','Palma','Primera FEB'),
('FUS Rabat','Morocco','Rabat','Division Excellence'),
('Galatasaray MCT Technic','Türkiye','Istanbul','Türkiye Basketbol Süper Ligi'),
('GAS Komotini','Greece','Komotini','Elite League'),
('Glafkos Esperos','Greece','Patras','Elite League'),
('Grupo Ureta Tizona Burgos','Spain','Burgos','Primera FEB'),
('GS Sofades','Greece','Sofades','Elite League'),
('Hangtuah Jakarta','Indonesia','Jakarta','IBL'),
('Hertener Löwen','Germany','Herten','ProB'),
('Hi-Tech Basketball Club','Thailand','Bangkok','Thailand Basketball League'),
('Iberojet Palencia','Spain','Palencia','Primera FEB'),
('Ittihad Tanger','Morocco','Tangier','Division Excellence'),
('Itzehoe Eagles','Germany','Itzehoe','ProB'),
('Iverioni','Georgia',null,'Superleague'),
('Jeanne d’Arc Dakar','Senegal','Dakar','National 1'),
('Johor Southern Tigers','Malaysia','Johor Bahru','Malaysian Basketball League'),
('Jozi Nuggets','South Africa','Johannesburg','Basketball National League'),
('JSA Bordeaux Basket','France','Bordeaux','NM1'),
('Karşıyaka','Türkiye','Izmir','Türkiye Basketbol Süper Ligi'),
('Kesatria Bengawan Solo','Indonesia','Surakarta','IBL'),
('KL Aseel','Malaysia','Kuala Lumpur','Malaysian Basketball League'),
('Koroivos','Greece','Amaliada','Elite League'),
('Kreisbau Kirchheim Knights','Germany','Kirchheim unter Teck','ProA'),
('Kronos Agiou Dimitriou','Greece','Agios Dimitrios','Elite League'),
('Kumanovo','North Macedonia','Kumanovo','North Macedonia SuperLeague'),
('Lavrio','Greece','Lavrio','Elite League'),
('Machites Peiramatikou Pefkon','Greece','Pefka','Elite League'),
('Mad Goat','Thailand','Bangkok','Thailand Basketball League'),
('Madzari 2003','North Macedonia','Skopje','North Macedonia SuperLeague'),
('Margveti','Georgia',null,'Superleague'),
('MAS Fès','Morocco','Fès','Division Excellence'),
('Mavericks','South Africa','Durban','Basketball National League'),
('MLP Academics Heidelberg','Germany','Heidelberg','ProA'),
('Mono Vampire','Thailand','Bangkok','Thailand Basketball League'),
('Motilones del Norte','Colombia','Cúcuta','Liga WPlay'),
('NS Matrix Deers','Malaysia','Seremban','Malaysian Basketball League'),
('Pacific Caesar Surabaya','Indonesia','Surabaya','IBL'),
('Panerythraikos','Greece','Nea Erythraia','Elite League'),
('Panionios','Greece','Nea Smyrni','Elite League'),
('Papagos','Greece','Athens','Elite League'),
('Pelita Jaya Basketball Jakarta','Indonesia','Jakarta','IBL'),
('Penang Sunrise Youngsters','Malaysia','Penang','Malaysian Basketball League'),
('Piratas de Bogotá','Colombia','Bogotá','Liga WPlay'),
('Proteas Voulas','Greece','Voula','Elite League'),
('Psychiko','Greece','Psychiko','Elite League'),
('Raja CA','Morocco','Casablanca','Division Excellence'),
('Rajawali Medan','Indonesia','Medan','IBL'),
('RANS Simba Bogor','Indonesia','Bogor','IBL'),
('Saint-Chamond Andrézieux-Bouthéon Basket','France','Saint-Chamond','NM1'),
('Sarawak Timberwolves','Malaysia','Kuching','Malaysian Basketball League'),
('Satria Muda Pertamina Bandung','Indonesia','Bandung','IBL'),
('Satya Wacana Salatiga','Indonesia','Salatiga','IBL'),
('SC Rist Wedel','Germany','Wedel','ProB'),
('Seawolves Academy','Germany','Rostock','ProB'),
('SG Braunschweig','Germany','Braunschweig','ProB'),
('Shoot It Dragons','Thailand','Bangkok','Thailand Basketball League'),
('SK Slavia Praha','Czechia','Prague','NBL'),
('SLUNETA Ústí nad Labem','Czechia','Ústí nad Labem','NBL'),
('Smouha','Egypt','Alexandria','Basketball Egyptian Super League'),
('Sokoli 1933','North Macedonia','Skopje','North Macedonia SuperLeague'),
('Soweto Panthers','South Africa','Soweto','Basketball National League'),
('Sporting Alexandria','Egypt','Alexandria','Basketball Egyptian Super League'),
('Strumica','North Macedonia','Strumica','North Macedonia SuperLeague'),
('Tangerang Hawks Basketball Club','Indonesia','Tangerang','IBL'),
('Telavi','Georgia','Telavi','Superleague'),
('TGE Thai Kruang Sanam','Thailand','Bangkok','Thailand Basketball League'),
('Tikvesh','North Macedonia','Kavadarci','North Macedonia SuperLeague'),
('Titanes de Barranquilla','Colombia','Barranquilla','Liga WPlay'),
('Tkibuli Olympic','Georgia','Tkibuli','Superleague'),
('Tofaş','Türkiye','Bursa','Türkiye Basketbol Süper Ligi'),
('Toros del Valle','Colombia','Cali','Liga WPlay'),
('TSG Solcom Ravens Reutlingen','Germany','Reutlingen','ProB'),
('Tshwane Suns','South Africa','Pretoria','Basketball National League'),
('TSV Neustadt temps Shooters','Germany','Neustadt','ProB'),
('Türk Telekom','Türkiye','Ankara','Türkiye Basketbol Süper Ligi'),
('US Laval Basket','France','Laval','NM1'),
('US Ouakam','Senegal','Dakar','National 1'),
('USK Praha','Czechia','Prague','NBL'),
('Vendée Challans Basket','France','Challans','NM1'),
('Vikos Falcons','Greece','Ioannina','Greek Basketball League'),
('Westports Malaysia Dragons','Malaysia','Kuala Lumpur','Malaysian Basketball League'),
('Wydad AC','Morocco','Casablanca','Division Excellence'),
('Zamalek','Egypt','Cairo','Basketball Egyptian Super League')
)
insert into public.teams(name,country,city,league_id,league_name,source,active)
select a.name,a.country,a.city,l.id,l.name,'manual-curated-global',true
from additions a join public.leagues l on lower(l.name)=lower(a.league_name) and lower(coalesce(l.country,''))=lower(a.country)
where not exists(select 1 from public.teams t where lower(t.name)=lower(a.name) and t.league_id=l.id);
